In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,101,10)

In [11]:
arr

array([50, 86, 55, 43, 79, 75,  9, 46, 49, 10])

In [12]:
np.sort(arr)

array([ 9, 10, 43, 46, 49, 50, 55, 75, 79, 86])

In [16]:
np.searchsorted(arr,25)

0

In [17]:
arr1=np.array([0,0,13,234,0,0,0,0,0,0])

In [20]:
np.count_nonzero(arr1)

2

In [21]:
np.where(arr1>10)

(array([2, 3], dtype=int64),)

In [24]:
np.extract(arr1>10,arr1)

array([ 13, 234])

In [25]:
arr.byteswap()

array([ 838860800, 1442840576,  922746880,  721420288, 1325400064,
       1258291200,  150994944,  771751936,  822083584,  167772160])

In [26]:
a=np.copy(arr)

In [27]:
a

array([50, 86, 55, 43, 79, 75,  9, 46, 49, 10])

In [28]:
b=arr.view()

In [31]:
b

array([50, 86, 55, 43, 79, 75,  9, 46, 49, 10])

In [32]:
import numpy.matlib as nm

In [35]:
nm.zeros((3,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [36]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [42]:
arr1=np.array([[2,3],[4,5]])

In [43]:
arr2=np.array([[5,3],[2,5]])

In [44]:
arr2

array([[5, 3],
       [2, 5]])

In [ ]:
np.do