In [1]:
import numpy as np

In [9]:
arr=np.random.randint(1,10,(3,4))

In [12]:
arr

array([[7, 8, 4, 3],
       [5, 6, 2, 6],
       [4, 2, 8, 8]])

In [13]:
arr.reshape(2,-232)

array([[7, 8, 4, 3, 5, 6],
       [2, 6, 4, 2, 8, 8]])

In [14]:
arr.T

array([[7, 5, 4],
       [8, 6, 2],
       [4, 2, 8],
       [3, 6, 8]])

In [15]:
arr.flatten()

array([7, 8, 4, 3, 5, 6, 2, 6, 4, 2, 8, 8])

In [16]:
arr1=np.array([1,2,3,4])

In [17]:
arr1.ndim

1

In [23]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4]])

In [24]:
arr

array([[7, 8, 4, 3],
       [5, 6, 2, 6],
       [4, 2, 8, 8]])

In [25]:
np.squeeze(arr)

array([[7, 8, 4, 3],
       [5, 6, 2, 6],
       [4, 2, 8, 8]])

In [27]:
data=np.array([[1],[2],[3]])

In [28]:
np.squeeze(data)

array([1, 2, 3])

In [29]:
arr1

array([1, 2, 3, 4])

In [30]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [31]:
np.roll(arr1,2)

array([3, 4, 1, 2])

In [32]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [33]:
arr1=np.random.randint(1,10,(3,3))

In [34]:
arr2=np.random.randint(1,10,(3,3))

In [35]:
arr2

array([[1, 1, 4],
       [3, 7, 1],
       [4, 6, 7]])

In [36]:
arr1+arr2

array([[ 4,  8,  7],
       [ 9, 16,  9],
       [10,  9, 10]])

In [39]:
arr1

array([[3, 7, 3],
       [6, 9, 8],
       [6, 3, 3]])

In [40]:
~arr1

array([[ -4,  -8,  -4],
       [ -7, -10,  -9],
       [ -7,  -4,  -4]])

In [41]:
arr1|arr2

array([[ 3,  7,  7],
       [ 7, 15,  9],
       [ 6,  7,  7]])

In [42]:
arr=np.array(['sudh','kumar'])

In [43]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [44]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [46]:
np.sin(arr1)

array([[ 0.14112001,  0.6569866 ,  0.14112001],
       [-0.2794155 ,  0.41211849,  0.98935825],
       [-0.2794155 ,  0.14112001,  0.14112001]])