In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

In [57]:
class Perceptron:
    def __init__(self,eta,epochs):
        self.weights=np.random.randn(3) * 1e-4
        print(f'self.weights: {self.weights}')
        self.eta=eta
        self.epochs=epochs
        
    def activation_function(self,inputs,weights):
        z=np.dot(inputs,weights)
        return np.where(z>0,1,0)
    
    def fit(self,X,y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]
        print(f'X_with_bias: \n{X_with_bias}')
    
        for epoch in range(self.epochs):
            print(f'for epoch: {epoch}')
            y_hat=self.activation_function(X_with_bias,self.weights)
            print(f'predicted value: \n{y_hat}')
            error=self.y - y_hat
            print(f'error: \n{error}')
            self.weights=self.weights+self.eta*np.dot(X_with_bias.T,error)
            print(f'updated weights: \n{self.weights}')
            
    def predict(self,X):
        X_with_bias=np.c_[X,-np.ones((len(self.X),1))]
        return self.activation_function(X_with_bias,self.weights)

In [46]:
data={'x1':[0,0,1,1],'x2':[0,1,0,1],'y':[0,0,0,1]}

In [47]:
AND = pd.DataFrame(data)

In [48]:
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [49]:
X=AND.drop('y',axis=1)

In [52]:
y=AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

In [53]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [54]:
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [58]:
model=Perceptron(eta=0.5,epochs=10)

self.weights: [ 7.53499866e-06 -5.44150182e-05  1.19774134e-04]


In [59]:
model.fit(X,y)

X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[ 0.50000753  0.49994558 -0.49988023]
for epoch: 1
predicted value: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
[ 7.53499866e-06 -5.44150182e-05  1.00011977e+00]
for epoch: 2
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[0.50000753 0.49994558 0.50011977]
for epoch: 3
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.50000753 0.49994558 0.50011977]
for epoch: 4
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.50000753 0.49994558 0.50011977]
for epoch: 5
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.50000753 0.49994558 0.50011

In [60]:
data={'x1':[0,0,1,1],'x2':[0,1,0,1],'y':[0,1,1,1]}

In [61]:
OR=pd.DataFrame(data)

In [62]:
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [64]:
X=OR.iloc[:,:-1]

In [65]:
y=OR.iloc[:,-1]

In [66]:
model.fit(X,y)

X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 0 0 1]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 1.00000753  0.99994558 -0.49988023]
for epoch: 1
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[1.00000753e+00 9.99945585e-01 1.19774134e-04]
for epoch: 2
predicted value: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[1.00000753e+00 9.99945585e-01 1.19774134e-04]
for epoch: 3
predicted value: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[1.00000753e+00 9.99945585e-01 1.19774134e-04]
for epoch: 4
predicted value: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[1.00000753e+00 9.99945585e-01 1.19774134e-04]
for epoch: 5
predicted value: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights

In [67]:
model.weights

array([1.00000753e+00, 9.99945585e-01, 1.19774134e-04])

In [68]:
model.predict(X)

array([0, 1, 1, 1])