In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
ar=np.array(l)

In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.asarray(l)

array([1, 2, 3, 4])

In [6]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [7]:
b=np.matrix(l)

In [8]:
b

matrix([[1, 2, 3, 4]])

In [9]:
a=np.array(l)

In [10]:
a

array([1, 2, 3, 4])

In [11]:
c=a

In [12]:
c[0]

1

In [13]:
d=a

In [14]:
d

array([1, 2, 3, 4])

In [15]:
a[1]=100

In [16]:
a

array([  1, 100,   3,   4])

In [17]:
d

array([  1, 100,   3,   4])

In [18]:
d=np.copy(a)

In [19]:
a[1]=200

In [20]:
a

array([  1, 200,   3,   4])

In [21]:
d

array([  1, 100,   3,   4])

In [22]:
np.fromfunction(lambda i,j:i==j,(3,3))  

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
itr=(i*i for i in range(5))
np.fromiter(itr,float)

array([ 0.,  1.,  4.,  9., 16.])

In [26]:
np.fromstring('23 54 76',sep=' ',dtype=int)

array([23, 54, 76])

In [27]:
ar2=np.array([[1,2],[3,4]])

In [28]:
ar2.ndim

2

In [29]:
ar2.size

4

In [30]:
ar.shape

(4,)

In [31]:
ar2.shape

(2, 2)

In [32]:
ar22=np.array([[1.4,23,21],[4,32,5]])

In [33]:
ar22.dtype

dtype('float64')

In [40]:
list(np.arange(2.3,5.6,0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [48]:
np.linspace(start=1,stop=5,num=5)

array([1., 2., 3., 4., 5.])

In [50]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [52]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [54]:
on=np.ones((2,3,2))

In [55]:
on+3

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [59]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [60]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.linspace(5,5.1,10)

array([5.        , 5.01111111, 5.02222222, 5.03333333, 5.04444444,
       5.05555556, 5.06666667, 5.07777778, 5.08888889, 5.1       ])

In [70]:
np.random.randn(3,4)

array([[ 0.19153464,  0.91525026, -0.54714842, -0.44459809],
       [ 2.20894643,  0.34406485,  0.02129229, -1.29833508],
       [ 0.01282614,  0.82241886, -0.89820319,  0.70161716]])

In [72]:
import pandas as pd

In [73]:
pd.DataFrame(np.random.randn(3,4))

0         1         2         3
0 -0.050478  1.020817 -1.003667  1.146224
1 -2.185105  0.137716 -0.416174  0.631063
2  0.824259  0.182784 -1.053834 -0.489211

In [79]:
arr=np.random.rand(3,4)

In [78]:
pd.DataFrame(np.random.randint(1,100,(3,4))).to_csv('test.csv')

In [82]:
arr1=arr.reshape(6,2)

In [84]:
arr1[1][1]

0.8314971071426696

In [86]:
arr=np.random.randint(1,100,(5,5))

In [87]:
arr

array([[79, 41, 64, 40, 57],
       [88, 14, 34, 36, 97],
       [20, 27, 49, 50, 83],
       [38, 56, 47,  9, 19],
       [70, 40, 55, 12, 97]])

In [88]:
arr[arr>50]

array([79, 64, 57, 88, 97, 83, 56, 70, 55, 97])

In [89]:
arr

array([[79, 41, 64, 40, 57],
       [88, 14, 34, 36, 97],
       [20, 27, 49, 50, 83],
       [38, 56, 47,  9, 19],
       [70, 40, 55, 12, 97]])

In [93]:
arr[2:4,[1,2]]

array([[27, 49],
       [56, 47]])

In [94]:
np.random.randint(1,100,(5,5))

array([[82,  9, 21, 59, 15],
       [90, 94, 23, 97, 41],
       [84, 54, 98, 12,  9],
       [38, 77,  5, 67, 47],
       [12, 53,  8, 93, 29]])

In [96]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [97]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [2, 2, 2]])

In [98]:
arr2

array([[2, 2, 2],
       [1, 2, 1],
       [2, 1, 1]])

In [100]:
arr1+arr2

array([[3, 4, 4],
       [2, 4, 3],
       [4, 3, 3]])

In [101]:
arr1*arr2

array([[2, 4, 4],
       [1, 4, 2],
       [4, 2, 2]])

In [102]:
arr1@arr2

array([[ 8,  8,  6],
       [ 8,  8,  6],
       [10, 10,  8]])

In [103]:
arr1/0

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15456\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [107]:
arr=np.zeros((4,4))

In [108]:
row=np.array([1,2,3,4])

In [109]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [110]:
col=np.array([[1,2,3,4]])

In [111]:
col.ndim

2

In [113]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])